build: 
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
watch:
	dotnet watch --project src/AdventOfCode/AdventOfCode.csproj run
start:
	dotnet run --project src/AdventOfCode/AdventOfCode.csproj
check:
	dotnet test

